### ISSUE TITLE
uninitialized constant Deface (NameError)

### ISSUE THREAD

**Issue by ashrafalzyoud** [nanego/redmine_admin_activity#50]
```
uninitialized constant Deface (NameError)
  /home/redmine/redmine.5-1/plugins/redmine_admin_activity/app/overrides/users/edit.rb:1:in `<top (required)>'
  <internal:/home/redmine/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
  <internal:/home/redmine/.rbenv/versions/3.2.3/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:26:in `require'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/helpers.rb:135:in `cget'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:175:in `block in actual_eager_load_dir'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/helpers.rb:25:in `each'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/helpers.rb:25:in `ls'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:170:in `actual_eager_load_dir'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:16:in `each'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:379:in `block in eager_load_all'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:377:in `each'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.13/lib/zeitwerk/loader.rb:377:in `eager_load_all'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/railties-6.1.7.7/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/railties-6.1.7.7/lib/rails/initializable.rb:32:in `instance_exec'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/railties-6.1.7.7/lib/rails/initializable.rb:32:in `run'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/railties-6.1.7.7/lib/rails/initializable.rb:61:in `block in run_initializers'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/3.2.0/tsort.rb:347:in `each'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/3.2.0/tsort.rb:347:in `call'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/railties-6.1.7.7/lib/rails/initializable.rb:60:in `run_initializers'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/railties-6.1.7.7/lib/rails/application.rb:391:in `initialize!'
  /home/redmine/redmine.5-1/config/environment.rb:16:in `<top (required)>'
  config.ru:3:in `require_relative'
  config.ru:3:in `block in <main>'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/rack-2.2.8.1/lib/rack/builder.rb:125:in `instance_eval'
  /home/redmine/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/rack-2.2.8.1/lib/rack/builder.rb:125:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:399:in `run_block_and_record_step_progress'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
```

**Comment by nanego** [comment]
The plugin has been updated to work even when the [redmine_base_deface](https://github.com/jbbarth/redmine_base_deface) plugin is not present.
The Deface plugin is required to display the history link in user pages (edit/show views).
